### ISSUE TITLE
The texture of the Simple Texture model of glTF 2.0 is upside down

### ISSUE THREAD

**Issue by cx20** [javagl/gltfTutorialModels#2]
I think that it is probably a mistake, but it seems that the orientation of the texture is reversed in glTF 1.1 and 2.0 models.

https://github.com/javagl/gltfTutorialModels/blob/master/SimpleTexture/glTF/square.bin
![image](https://cloud.githubusercontent.com/assets/1833979/22627737/4694d0e2-ec0b-11e6-9adc-4e8557e3cb3f.png)

https://github.com/javagl/gltfTutorialModels/blob/2.0/SimpleTexture/glTF/square.bin
![image](https://cloud.githubusercontent.com/assets/1833979/22627741/5347d726-ec0b-11e6-83be-ed3f1ab28de0.png)

**Comment by javagl** [comment]
Drawing the connection between https://github.com/javagl/JglTF/issues/10#issuecomment-269810809 and more importantly https://github.com/AnalyticalGraphicsInc/cesium/pull/4808#issuecomment-275548620 - and as you can see in these links: It's difficult. 

The texture coordinates have been flipped for the 2.0 version of the models, as per request in the second link. 

Ironically, this was *supposed* to avoid confusion ;-) 

However, now I have also updated the texture image (the PNG file), and added a note in the README at https://github.com/javagl/gltfTutorialModels/blob/master/SimpleTexture/README.md , emphasizing that the *texture image now actually shows the real texture coordinates*. 

Also, another disclaimer: **Much of the discussion around 2.0 is not finalized. The models here are highly preliminary.**

**Comment by cx20** [comment]
I am confused again. :-(
Is it correct that the results of Screenshot and glTF Loader are different?

<table>
<tr>
<th>Version</th>
<th>Texture</th>
<th>README's Screenshot</th>
<th>Three.js result</th>
</tr>
<tr>
<td>glTF Tutorial 1.1</td>
<td><img src="https://github.com/javagl/gltfTutorialModels/blob/master/SimpleTexture/glTF/testTexture.png?raw=true"></img></td>
<td><img src="https://github.com/javagl/gltfTutorialModels/raw/master/SimpleTexture/screenshot/screenshot.png"></img></td>
<td><img src="https://cloud.githubusercontent.com/assets/1833979/22650837/2a7a8596-ecc4-11e6-9904-826f884f7d9d.png"></img></td>
</tr>
<tr>
<td>glTF Tutorial 2.0</td>
<td><img src="https://cloud.githubusercontent.com/assets/1833979/22691588/826ebe60-ed7e-11e6-8586-f373c504c050.png"></img></td>
<td><img src="https://cloud.githubusercontent.com/assets/1833979/22691609/97ed61b0-ed7e-11e6-8113-3e28bf9c6f04.png"></img></td>
<td><img src="https://cloud.githubusercontent.com/assets/1833979/22650894/591ed596-ecc4-11e6-96d5-11fc78f96e4b.png"></img></td>
</tr>
</table>

**Comment by javagl** [comment]
Sorry, this....

> The texture coordinates have been flipped for the 2.0 version of the models, as per request in the second link.

... was misleading: **The 2.0 branch is not yet completely updated!**

Particularly, the "SimpleTexture" model in the 2.0 branch is **older** than the "SimpleTexture" model in the 1.1 branch. In the 1.1 branch, the texture is flipped and the texture coordinates are updated. In the 2.0 branch, this is not done yet.

The following models have been updated to 2.0, as far as this is possible:

    Triangle
    TriangleWithoutIndices     
    AnimatedTriangle
    Cameras
    SimpleMeshes
    SimpleMaterial

But these models are still in an old 1.1-ish state:
    
    SimpleOpacity
    SimpleSkin
    SimpleTexture

Sorry, I know that this is a mess. But the update to 2.0 came like a bolt from the blue. The changes between 1.0 and 2.0 mean that much of the existing code basically has to be rewritten or at least *heavily* refactored. Beyond that, it's still not clear whether the tutorial should cover PBR (which is still *far* from being finalized), or whether the tutorial models should be based on PBR or on `KHR_technique_webgl` (which isn't finalized either). 

The best thing would probably be to not rely on this `gltfTutorialModels` repository until the dust around 2.0 has settled. (Also see https://github.com/KhronosGroup/glTF-Sample-Models/pull/27#issuecomment-277721028 )

**Comment by cx20** [comment]
> The 2.0 branch is not yet completely updated!

I understood. I will try again when the model is updated.

**Comment by javagl** [comment]
@cx20 I have pushed the latest state at https://github.com/javagl/gltfTutorialModels/commit/7dfcda630d21bfa36de796f09b7772ceadf1eb78 , but again: This should be considered as preliminary. I think it does not really make sense to test loaders and viewers against glTF 2.0 when glTF 2.0 *and* the extension that is required to use techniques+programs+shaders are not finalized yet...

**Comment by cx20** [comment]
The SimpleTexture model is not displayed in the latest version.
https://github.com/javagl/gltfTutorialModels/commit/2db67bc3f473905b54a13f84a89de40352dd3893#diff-100fee0de5023bc5ec08ae270ece77b0R66

>      "uri": "unitSquare0.bin", 

It seems that unitSquare0.bin does not exist.

> This should be considered as preliminary. 

I think so, too. I would like to update the sample again when the specifications have made progress.

**Comment by javagl** [comment]
Right now, I cannot even test the models myself - I have not yet set up the infrastructure to load 2.0. There also is no validator for 2.0, so *using* these models probably does not make sense. 

I'll notify you when they are merged into `master` (here or in the Khronos repo), and when they can be used for first tests.

**Comment by javagl** [comment]
The `SimpleTexture` model that will be added to the glTF-Sample-Assets repo as part of https://github.com/KhronosGroup/glTF-Sample-Assets/pull/90 should have the right texture.
