### ISSUE TITLE
glTF 2.0 tutorial model in Khronos' glTF-Sample-Models seems to be incomplete

### ISSUE THREAD

**Issue by cx20** [javagl/gltfTutorialModels#3]
I noticed that the tutorial model in Khronos' glTF-Sample-Models remained old.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0

|gltfTutorialModels (2.0 branch)|asset version|glTF-Sample-Models          |
|:------------------------------|:-----------:|:---------------------------|
|TriangleWithoutIndices         |2.0          |2.0/TriangleWithoutIndices  |
|Triangle                       |2.0          |2.0/Triangle                |
|AnimatedTriangle               |2.0          |2.0/AnimatedTriangle        |
|SimpleMaterial                 |2.0          |:x:                         |
|SimpleMeshes                   |2.0          |2.0/SimpleMeshes            |
|AdvancedMaterial               |1.1          |:x:                         |
|SimpleOpacity                  |1.1          |:x:                         |
|SimpleTexture                  |2.0          |:x:                         |
|Cameras                        |2.0          |2.0/Cameras                 |
|Simple Skin                    |2.0          |:x:                         |

The model of gltfTutorialModels should also be placed in glTF-Sample-Models.
I think that `SimpleMaterial`, `SimpleTexture`, `SimpleSkin` are the subjects.

However, it appears that `SimpleTexture` and `SimpleSkin` can not be displayed in other libraries (Three.js, Babylon.js, etc). Is this model WIP?

**Comment by javagl** [comment]
The models have mostly been updated for the tutorial, so they basically exist (for example, the `SimpleTexture` is at https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_013_SimpleTexture.md )

Two new models for testing the 2.0 features are in this pending PR: https://github.com/KhronosGroup/glTF-Sample-Models/pull/132

This repo here will be updated soon (although there are some higher priority tasks in the queue right now...)

**Comment by javagl** [comment]
And wooosh... only 7 years later, this is done 😃 

At least, the pending updates are tracked in https://github.com/KhronosGroup/glTF-Sample-Assets/issues/70 (and _this_ repo is no longer used for actively maintaining the tutorial models anyhow)
